## Numpy 배열

In [3]:
x = [1, 3, 5]
x.mean()

AttributeError: 'list' object has no attribute 'mean'

In [5]:
import numpy as np

x = np.array([1, 3, 5])
print(x.mean())

3.0


In [6]:
print(x.shape)

(3,)


In [7]:
a = np.array([[1, 2, 3], [2, 3, 4]])

In [8]:
print(a.shape)

(2, 3)


In [11]:
x = np.array([1, 3, 5, 7, 9, 11]).reshape(3, 2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [12]:
y = np.ones([3, 4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
x = np.array([[1, 3, 5], [2, 4, 6]])
print(x[1])
print(x[1].mean())
print(x.mean())
print(x.shape)

[2 4 6]
4.0
3.5
(2, 3)


In [15]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[1][1])

12


## Numpy 배열의 슬라이싱

In [16]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:][1])

[2, 12]


In [17]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:, 1])

TypeError: list indices must be integers or slices, not tuple

In [18]:
np_ary = np.array(list1)
print(np_ary[:, 1])

[11 12 13]


In [20]:
print(np.array(list1[:, 1]))

TypeError: list indices must be integers or slices, not tuple

In [21]:
list1 = np.array([[1, 11], [2, 12], [3, 13]])
print(list1[:, 1])

[11 12 13]


In [22]:
list1 = [[1, 11], [2, 12], [3, 13]]

print(np.array(list1[:, 1]))

TypeError: list indices must be integers or slices, not tuple

## Numpy를 이용한 연산

In [23]:
import math
math.sqrt(2)

1.4142135623730951

In [24]:
math.sqrt([2, 3, 4])

TypeError: must be real number, not list

In [25]:
np.sqrt([2, 3, 4])

array([1.41421356, 1.73205081, 2.        ])

In [26]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 제로 벡터와 제로 행렬

In [28]:
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [29]:
zero_matrix = np.zeros((4,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
my_array = np.zeros(15).reshape(3,5)
my_array += 4
my_array

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

## 전치행렬

In [32]:
ary = [[1, 2], [3, 4]]
print(ary.transpose())

AttributeError: 'list' object has no attribute 'transpose'

In [33]:
ary = np.array([[1, 2], [3, 4]])
print(ary.transpose())

[[1 3]
 [2 4]]


In [34]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x + y

print(z)

[5 7 9]


In [35]:
s = [1, 2, 3]
t = s + 1
print(t)

TypeError: can only concatenate list (not "int") to list

In [36]:
s = np.array([1, 2, 3])
t = s + 1
print(t)

[2 3 4]


In [37]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(X[1])
print(X[:, 1])

[4 5 6]
[2 5 8]


In [38]:
Y = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(X[:, 1] + Y[:, 1])

[ 5 11 17]


In [39]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[20 40 60]


In [40]:
b = np.array(a[1:6:2])
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

## 불리언(Boolean)

In [41]:
b = a > 50
print(b)

[False False False False False  True  True]


In [42]:
ary = np.random.random(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary > 0.7))

[0.22099411 0.11072507 0.48866413 0.78237919 0.22823771]
False
True


## 등간격 나누기

In [43]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [44]:
np.linspace(0, 12, 4, retstep=True)

(array([ 0.,  4.,  8., 12.]), 4.0)

In [45]:
np.linspace(0, 12, 4, endpoint=False)

array([0., 3., 6., 9.])

In [46]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [47]:
np.logspace(1, 2, 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])